# set CPack options
install (FILES ${CMAKE_CURRENT_SOURCE_DIR}/cpack/LICENSE.pdf DESTINATION doc)
install (FILES ${CMAKE_CURRENT_SOURCE_DIR}/cpack/README.txt DESTINATION doc)
set (CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/cpack/description.txt)
set (CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/cpack/license.txt)
set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "A tool for fast automatic 3D-stitching of teravoxel-sized microscopy images")
set (CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR} )
set (CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR} )
set (CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH} )